# -*- coding: utf-8 -*-
"""Detecção-de-Anomalias-em-Transações-Bancárias-com-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPw4zc3M5ysDN1gagP7sY33Rrqm7WkX1

**DETECÇÃO DE ANOMALIAS EM TRANSAÇÕES BANCÁRIAS COM PYTHON**
"""

import pandas as pd

url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

df = pd.read_csv(url)

df.head()

"""**Problema de classificação desbalanceada**

Transações Normais = 0

Transações Fraudulentas = 1

"Fraudes são raras, e isso faz com que o modelo possa ignorar a classe 1."
"""

df["Class"].value_counts(normalize=True)

"""**Feature Engineering**

Criando variáveis que ajudam o modelo
"""

import numpy as np

df["Amount_log"] = np.log1p(df["Amount"])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])

from sklearn.model_selection import train_test_split

x = df.drop("Class", axis=1)
y = df["Class"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, stratify=y, test_size=0.3, random_state=42
)

"""**Logistic Regression**"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""Accuracy pode ser alta mesmo sem detectar fraudes.

Por isso usamos:

- Recall (mais importante)

- Precision

- F1-score
"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_probs = model.predict_proba(x_test)[:,1]

fpr, tpr, _ = roc_curve(y_test, y_probs)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

print("AUC:", roc_auc_score(y_test, y_probs))

from sklearn.metrics import precision_recall_curve

precisions, recalls, _ = precision_recall_curve(y_test, y_probs)

plt.plot(recalls, precisions)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""**Balanceamento de dados**"""

# Undersampling - vai reduzir a classe majoritária
fraudes = df[df["Class"] == 1]
normais = df[df["Class"] == 0].sample(len(fraudes), random_state=42)

df_under = pd.concat([fraudes, normais])

# Oversampling - vai aumentar a classe minoritária
from imblearn.over_sampling import SMOTE

smote = SMOTE()

x_res, y_res = smote.fit_resample(x, y)

# Undersampling ou Oversampling? Qual a melhor escolha? Depende, vai ter que testar para saber ...

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight="balanced",
    n_jobs=1,
    random_state=42
)

rf.fit(x_train, y_train)
y_pred_rf = rf.predict(x_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(x_train, y_train)

y_pred = pipeline.predict(x_test)

threshold = 0.3

y_pred_custom = (y_probs > threshold).astype(int)

print(classification_report(y_test, y_pred_custom))

"""**Modelo Avançado - XGBoost**

XGBoost é um dos algoritimos mais usados em competições e mercado.

Ele é mais poderoso que Random Forest para muitos problemas.

"""

from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=10,   # ajuda com desbalanceamento
    use_label_encoder=False,
    eval_metric="logloss"
)

xgb.fit(x_train, y_train)

y_pred_xgb = xgb.predict(x_test)

print(classification_report(y_test, y_pred_xgb))

"""**Importância das variáveis**

Ajuda a entender quais variáveis influenciam mais o modelo.
"""

import matplotlib.pyplot as plt

importancias = xgb.feature_importances_

plt.bar(range(len(importancias)), importancias)
plt.title("importância das variáveis")
plt.show()

"""**Ajuste de hiperparâmentros**

Testamos várias combinações para melhorar o modelo.
"""

from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

param_grid = {
    "max_depth": [3, 5],
    "n_estimators": [50, 100]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
    param_grid,
    scoring="recall",
    cv=3
)

grid.fit(x_train, y_train)

print("Melhor modelo:", grid.best_params_)

"""**Explicabilidade (SHAP)**

SHAP mostra como cada variável influencia a decisão do modelo.
"""

import shap

explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])

shap.plots.bar(shap_values)